<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="10" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="2519" started-at="2015-10-30T22:25:23Z" finished-at="2015-10-30T22:25:25Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="2519" started-at="2015-10-30T22:25:23Z" finished-at="2015-10-30T22:25:25Z">
      <class name="cz.muni.fi.pa165.project.ServiceCheckTest">
        <test-method status="PASS" signature="ServiceCheckInsertTest()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="ServiceCheckInsertTest" duration-ms="35" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ServiceCheckInsertTest -->
        <test-method status="PASS" signature="findAllVehiclesAndServiceChecks()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="findAllVehiclesAndServiceChecks" duration-ms="78" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findAllVehiclesAndServiceChecks -->
        <test-method status="PASS" signature="ServiceCheckUpdateTest()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="ServiceCheckUpdateTest" duration-ms="47" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ServiceCheckUpdateTest -->
        <test-method status="PASS" signature="ServiceCheckDeleteTest()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="ServiceCheckDeleteTest" duration-ms="46" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ServiceCheckDeleteTest -->
        <test-method status="PASS" signature="testDoubleDeletionException()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="testDoubleDeletionException" duration-ms="24" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at cz.muni.fi.pa165.project.ServiceCheckTest.testDoubleDeletionException(ServiceCheckTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at cz.muni.fi.pa165.project.dao.ServiceCheckDaoImpl.deleteServiceCheck(ServiceCheckDaoImpl.java:58)
	at cz.muni.fi.pa165.project.ServiceCheckTest.testDoubleDeletionException(ServiceCheckTest.java:198)
	... 34 more
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:81)
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:73)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:63)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3400)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3630)
	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:114)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	at cz.muni.fi.pa165.project.dao.ServiceCheckDaoImpl.deleteServiceCheck(ServiceCheckDaoImpl.java:55)
	... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoubleDeletionException -->
        <test-method status="PASS" signature="testUpdateAfterDelete()[pri:0, instance:cz.muni.fi.pa165.project.ServiceCheckTest@1e643faf]" name="testUpdateAfterDelete" duration-ms="1" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.TransactionException: nested transactions not supported]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.TransactionException: nested transactions not supported
	at cz.muni.fi.pa165.project.ServiceCheckTest.testUpdateAfterDelete(ServiceCheckTest.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: cz.muni.fi.pa165.project.util.HibernateErrorException: org.hibernate.TransactionException: nested transactions not supported
	at cz.muni.fi.pa165.project.dao.ServiceCheckDaoImpl.findServiceCheck(ServiceCheckDaoImpl.java:75)
	at cz.muni.fi.pa165.project.ServiceCheckTest.testUpdateAfterDelete(ServiceCheckTest.java:208)
	... 34 more
Caused by: org.hibernate.TransactionException: nested transactions not supported
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:154)
	at cz.muni.fi.pa165.project.dao.ServiceCheckDaoImpl.findServiceCheck(ServiceCheckDaoImpl.java:66)
	... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateAfterDelete -->
      </class> <!-- cz.muni.fi.pa165.project.ServiceCheckTest -->
      <class name="cz.muni.fi.pa165.project.EmployeeTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:cz.muni.fi.pa165.project.EmployeeTest@3d24753a]" name="initialize" is-config="true" duration-ms="15" started-at="2015-10-30T23:25:23Z" finished-at="2015-10-30T23:25:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="employeeCreateTest()[pri:0, instance:cz.muni.fi.pa165.project.EmployeeTest@3d24753a]" name="employeeCreateTest" duration-ms="2181" started-at="2015-10-30T23:25:23Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- employeeCreateTest -->
        <test-method status="PASS" signature="employeeFindTest()[pri:0, instance:cz.muni.fi.pa165.project.EmployeeTest@3d24753a]" name="employeeFindTest" duration-ms="24" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- employeeFindTest -->
        <test-method status="PASS" signature="employeeUpdateTest()[pri:0, instance:cz.muni.fi.pa165.project.EmployeeTest@3d24753a]" name="employeeUpdateTest" duration-ms="22" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- employeeUpdateTest -->
        <test-method status="PASS" signature="employeeDeleteTest()[pri:0, instance:cz.muni.fi.pa165.project.EmployeeTest@3d24753a]" name="employeeDeleteTest" duration-ms="20" started-at="2015-10-30T23:25:25Z" finished-at="2015-10-30T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- employeeDeleteTest -->
      </class> <!-- cz.muni.fi.pa165.project.EmployeeTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
